const movies = [
  {
    title: "RRR",
    slug: "rrr",
    genre: ["Action", "Drama"],
    language: "Telugu",
    poster: "https://media.themoviedb.org/t/p/w440_and_h660_face/nEufeZlyAOLqO2brrs0yeF1lgXO.jpg",
    trailer: "https://youtu.be/NgBoMJy386M?si=OkOstTJ4SxMF6AbQ",
    imdbRating: 8.0,
    releaseYear: 2022,
    duration: "3h 7m",
  },
  {
    title: "Baahubali: The Beginning",
    slug: "baahubali-the-beginning",
    genre: ["Action", "Fantasy"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/9BAjt8nSSms62uOVYn1t3C3dVto.jpg",
    trailer: "https://youtu.be/sOEg_YZQsTI?si=BCPArW4UE9UET5tA",
    imdbRating: 8.1,
    releaseYear: 2015,
    duration: "2h 39m",
  },
  {
    title: "Baahubali: The Conclusion",
    slug: "baahubali-the-conclusion",
    genre: ["Action", "Fantasy"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/xQ22LOWSkClP3maYhR9nZH0dnWM.jpg",
    trailer: "https://youtu.be/qD-6d8Wo3do?si=CbC9O1B0gEkovpqq",
    imdbRating: 8.2,
    releaseYear: 2017,
    duration: "2h 47m",
  },
  {
    title: "Salaar",
    slug: "salaar",
    genre: ["Action", "Thriller"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/mNHdClul57prczb5O0krrzyonnn.jpg",
    trailer: "https://youtu.be/4GPvYMKtrtI?si=MUoozTmrwaKUwkCv",
    imdbRating: 8.0,
    releaseYear: 2023,
    duration: "2h 55m",
  },
  {
    title: "KGF Chapter 1",
    slug: "kgf-chapter-1",
    genre: ["Action", "Crime"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/5p41FuorOtmVbfD6TT2lFldOCzs.jpg",
    trailer: "https://youtu.be/fnGW4iQzVLw?si=IUHH5opge4KgD3Pd",
    imdbRating: 8.2,
    releaseYear: 2018,
    duration: "2h 36m",
  },
  {
    title: "KGF Chapter 2",
    slug: "kgf-chapter-2",
    genre: ["Action", "Thriller"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/khNVygolU0TxLIDWff5tQlAhZ23.jpg",
    trailer: "https://youtu.be/bDTUFufX-1s?si=t8Cv-hNWqF05j2Ey",
    imdbRating: 8.3,
    releaseYear: 2022,
    duration: "2h 48m",
  },
  {
    title: "The Avengers",
    slug: "the-avengers",
    genre: ["Action", "Sci-Fi"],
    language: "English",
    poster: "https://www.themoviedb.org/t/p/w1280/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    trailer: "https://youtu.be/eOrNdBpGMv8?si=PMH8YCEGKioE1ZoQ",
    imdbRating: 8.0,
    releaseYear: 2012,
    duration: "2h 23m",
  },
  {
    title: "Avengers: Endgame",
    slug: "avengers-endgame",
    genre: ["Action", "Sci-Fi"],
    language: "English",
    poster: "https://www.themoviedb.org/t/p/w1280/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
    trailer: "https://youtu.be/TcMBFSGVi1c?si=H6N1L41I32Jkm721",
    imdbRating: 8.4,
    releaseYear: 2019,
    duration: "3h 1m",
  },
  {
    title: "Spider-Man: No Way Home",
    slug: "spider-man-no-way-home",
    genre: ["Action", "Adventure"],
    language: "English",
    poster: "https://www.themoviedb.org/t/p/w1280/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    trailer: "https://youtu.be/JfVOs4VSpmA?si=XHRW6oBU36HepnGd",
    imdbRating: 8.3,
    releaseYear: 2021,
    duration: "2h 28m",
  },
  {
    title: "Spider-Man: Homecoming",
    slug: "spider-man-homecoming",
    genre: ["Action", "Adventure"],
    language: "English",
    poster: "https://www.themoviedb.org/t/p/w1280/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
    trailer: "https://youtu.be/rk-dF1lIbIg?si=ha0kMod8PgF6lVUZ",
    imdbRating: 7.4,
    releaseYear: 2017,
    duration: "2h 13m",
  },
  {
    title: "Spider-Man: Far From Home",
    slug: "spider-man-far-from-home",
    genre: ["Action", "Adventure"],
    language: "English",
    poster: "https://www.themoviedb.org/t/p/w1280/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
    trailer: "https://youtu.be/Nt9L1jCKGnE?si=WLfdoiS58EQLvLZM",
    imdbRating: 7.5,
    releaseYear: 2019,
    duration: "2h 9m",
  },
  {
    title: "Doctor Strange",
    slug: "doctor-strange",
    genre: ["Action", "Fantasy"],
    language: "English",
    poster: "https://www.themoviedb.org/t/p/w1280/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
    trailer: "https://youtu.be/aWzlQ2N6qqg?si=CBb-J1zMHjM_TEyT",
    imdbRating: 7.5,
    releaseYear: 2016,
    duration: "1h 55m",
  },
  {
    title: "Black Panther",
    slug: "black-panther",
    genre: ["Action", "Sci-Fi"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    trailer: "https://youtu.be/XF-_U0X1Sig?si=v5EkPOPn99w6HHMV",
    imdbRating: 7.3,
    releaseYear: 2018,
    duration: "2h 14m",
  },
  {
    title: "Vikram",
    slug: "vikram",
    genre: ["Action", "Thriller"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/774UV1aCURb4s4JfEFg3IEMu5Zj.jpg",
    trailer: "https://youtu.be/WC5X3i0B4cg?si=9Inh9WF45MC6m5uy",
    imdbRating: 8.3,
    releaseYear: 2022,
    duration: "2h 53m",
  },
  {
    title: "Drishyam 2",
    slug: "drishyam-2",
    genre: ["Crime", "Drama"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/mKHsiNOoOnFRBap5HSVO8kLhJGF.jpg",
    trailer: "https://youtu.be/uUJtUYkBu-g?si=3DlNoLGxy1rhrfC1",
    imdbRating: 8.2,
    releaseYear: 2022,
    duration: "2h 20m",
  },
  {
    title: "Oppenheimer",
    slug: "oppenheimer",
    genre: ["Biography", "Drama"],
    language: "English",
    poster: "https://www.themoviedb.org/t/p/w1280/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    trailer: "https://youtu.be/yi363I5MoAk?si=wbBErYjzq4nT8Ilg",
    imdbRating: 8.6,
    releaseYear: 2023,
    duration: "3h 0m",
  },
  {
    title: "The Batman",
    slug: "the-batman",
    genre: ["Action", "Crime"],
    language: "English",
    poster: "https://www.themoviedb.org/t/p/w1280/iuzJlMKV6FwHdl1CYV6UzNW6Qne.jpg",
    trailer: "https://youtu.be/mqqft2x_Aa4?si=OXrR1HKiYQ7hqgag",
    imdbRating: 7.8,
    releaseYear: 2022,
    duration: "2h 56m",
  },
  {
    title: "Ala Vaikunthapurramuloo",
    slug: "ala-vaikunthapurramuloo",
    genre: ["Action", "Drama"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/233ti0r8xKsbbQSsV4UAbFN2bWM.jpg",
    trailer: "https://youtu.be/SkENAjfVoNI?si=BuKfBMUs2gBI5hNV",
    imdbRating: 7.3,
    releaseYear: 2020,
    duration: "2h 45m"
  },
  {
    title: "Eega",
    slug: "eega",
    genre: ["Action", "Fantasy"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/xbCPJejbJgRIuOwUzJqcBUjCbFB.jpg",
    trailer: "https://youtu.be/x-1ZoU1xB4I?si=xFNH2hv8wtzN_5px",
    imdbRating: 7.7,
    releaseYear: 2012,
    duration: "2h 25m"
  },
  {
    title: "Arjun Reddy",
    slug: "arjun-reddy",
    genre: ["Drama", "Romance"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/kHubDgL59I5hCn7ccBYvU7bKY1r.jpg",
    trailer: "https://youtu.be/aozErj9NqeE?si=3fM--_xb5Bmgc733",
    imdbRating: 8.0,
    releaseYear: 2017,
    duration: "3h 2m"
  },
  {
    title: "Jersey",
    slug: "jersey",
    genre: ["Drama", "Sport"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/bU9q9yVtxeBiC0Do27CekHXNE6D.jpg",
    trailer: "https://youtu.be/AjAe_Q1WZ_8?si=_UJBl2JXnvBaDb4Q",
    imdbRating: 8.5,
    releaseYear: 2019,
    duration: "2h 40m"
  },
  {
    title: "Mahanati",
    slug: "mahanati",
    genre: ["Biography", "Drama"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/5hwtlwoLdSpkoeusT0sf8qW5VFB.jpg",
    trailer: "https://youtube.com/mahanati_trailer",
    imdbRating: 8.5,
    releaseYear: 2018,
    duration: "2h 57m"
  },
  {
    title: "Mirchi",
    slug: "mirchi",
    genre: ["Action", "Drama"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/5kzVcuY1tExm1zQAP9B2VEPsUb5.jpg",
    trailer: "https://youtu.be/OrnYMmWBuV4?si=SpAwBGgNhb_aCd-i",
    imdbRating: 7.2,
    releaseYear: 2013,
    duration: "2h 35m"
  },
  {
    title: "Sarileru Neekevvaru",
    slug: "sarileru-neekvvaru",
    genre: ["Action", "Comedy"],
    language: "Telugu",
    poster: "https://www.themoviedb.org/t/p/w1280/6bJNy4oHbRawb6j3FN2JAuKw7uh.jpg",
    trailer: "https://youtu.be/Pim3CUGCXbY?si=Af505yQ1-K34MiKy",
    imdbRating: 6.1,
    releaseYear: 2020,
    duration: "2h 49m"
  },
];

export default movies;
